### ISSUE TITLE
feat: create client feedback API

### ISSUE THREAD

**Issue by tanishdotdev** [bluppco/mmfinfotech.com#5]
Slug: 5ef6acda31014c11ac040eb25499d109

Add these fields:

- [ ] Name ( title )
- [ ] Slug ( formula )
- [ ] Designation ( rich_text )
- [ ] Description ( rich_text )
- [ ] Order ( number )
- [ ] Is Active ( checkbox )
- [ ] Display on Home ( checkbox )
- [ ] has_order = true
- [ ] has_md = f
- [ ] has_images = f

**Comment by devdotmohit** [comment]
@tanishdotdev calling this feedback.

**Comment by tanishdotdev** [comment]
> @tanishdotdev calling this feedback.

Noted.
